encoding: utf-8
timezone: Asia/Tokyo

# Site settings
title: nekketsu^ω
title-math: \mathsf{nekketsu}^\omega
description:  I'm nekketsuuu (ω)
baseurl: ""
reveal_path: /reveal.js/
url: "https://nekketsuuu.github.io"
twitter_username: nekketsuuu
github_username:  nekketsuuu

defaults:
  -
    scope:
      path: "entries"
    values:
      layout: "entry"
  -
    scope:
      path: "slides"
    values:
      layout: "slide"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
future: true
