encoding: utf-8
timezone: Asia/Tokyo

exclude:
  - ISSUE_TEMPLATE.md

# Site settings
title: nekketsu^ω
title_math: \mathsf{nekketsu}^\omega
description:  I'm nekketsuuu (ω)
baseurl: ""
url: "https://nekketsuuu.github.io"
twitter_username: nekketsuuu
github_username:  nekketsuuu
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: "entries"
    values:
      layout: "entry"

exclude:
  - "slides"
  - "assets/slides"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
future: true
