encoding: utf-8
timezone: Asia/Tokyo

# Site settings
title: nekketsu^ω
title_math: \mathsf{nekketsu}^\omega
description:  I'm nekketsuuu (ω)
baseurl: ""
reveal_path: /reveal.js/
url: "https://nekketsuuu.github.io"
twitter_username: nekketsuuu
github_username:  nekketsuuu

defaults:
  -
    scope:
      path: "entries"
    values:
      layout: "entry"
  -
    scope:
      path: "slides"
    values:
      layout: "slide"

# For writing markdown for slide easily
slide:
  begin: '<section data-markdown><script type="text/template">'
  end: '</script></section>'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
future: true
